plp_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plp_ecommerce/',include('plp_ecommerce.urls')),
]

plp_ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'plp_ecommerce'

urlpatterns = [
    path('', views.home, name='home'),
    path('product_list/', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('customers/<int:pk>/', views.customer_detail, name='customer_detail'),
]

plp_ecommerce/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    availability =models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=300)
    address = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='customers/')

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

plp_ecommerce/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from .models import Customer

# Create your views here.
def home(request):
    return render(request, 'plp_ecommerce/home.html')

def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'plp_ecommerce/product_list.html', context)

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context ={
        'product': product
    }
    return render(request, 'plp_ecommerce/product_detail.html', context)

def customer_list(request):
    customers =Customer.objects.all()
    context = {
        'customers': customers
    }
    return render(request, 'plp_ecommerce/customer_list.html', context)

def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    context ={
        'customer': customer
    }
    return render(request, 'plp_ecommerce/customer_detail.html', context)

plp_ecommerce/templates/plp_ecommerce/customer_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Customer Details</h1>
    <div class="container">
        <div class="customer_details">
            <h1>{{customer.first_name}}{{customer.last_name}}</h1>
            <p>><strong>Phone:</strong>{{customer.phone}}</p>
            <p>><strong>Email:</strong>{{customer.email}}</p>
            <p>><strong>Address:</strong>{{customer.address}}</p>
            <p>><strong>Joined on:</strong>{{customer.created_at}}</p>
        </div>

    </div>
<a href="{% url 'plp_ecommerce:customer_list'%}" class="back-link">Back to Customer List</a>

</body>

</html>

plp_ecommerce/templates/plp_ecommerce/customer_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer List</title>
</head>

<body>
    <h1>Customer List</h1>
    <ul>
        {% for customer in customers %}
        <li>
            <a href="{% url 'plp_ecommerce:customer_detail' customer.pk %}">
                {{ customer.first_name }} {{ customer.last_name }} ({{ customer.email }})
            </a>
        </li>


        {% endfor %}
    </ul>
<a href="{% url 'plp_ecommerce:customer_detail' %} "class="back-link">Add Customers</a>

</body>

</html>

plp_ecommerce/templates/plp_ecommerce/home.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/plp_ecommerce/style.css}">
    <title>Home</title>
</head>

<body>
    <h1>Welcome to PLP E-commerce</h1>
    <nav>
        <ul>
            <li><a href="{% url 'plp_ecommerce:product_list' %}">Product List</a></li>
            <li><a href="{% url 'plp_ecommerce:customer_list' %}">Customer List</a></li>
        </ul>
    </nav>
</body>

</html>

plp_ecommerce/templates/plp_ecommerce/product_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{product.name}}</title>
</head>

<body>

    <ul>
        {% for product in product %}
        <li>
            <h2>{{product.name}}</h2>
            <p>{{product.decription}}</p>
            <p>Price: Kshs.{{product.price}}</p>
            <img src="{{product.image.url}}" alt="{{product.name}}">
            <p>Availability:{{product.availability|yesno:"Yes, No"}}</p>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url 'plp_ecommerce:product_list'%}" class="back-link">Back to Product List</a>

</body>

</html>

plp_ecommerce/templates/plp_ecommerce/product_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>

<body>
    <h1>Products</h1>
    <ul>
        {% for product in products %}
        <li>
            <h2>{{ product.name }}</h2>
            <p>{{ product.description }}</p> 
            <p>Price: {{ product.price }}</p>
            {% if product.image %}
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            {% endif %}
            <br>
            <a href="{% url 'plp_ecommerce:product_detail' product.pk %}">View Details</a> 
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'plp_ecommerce:product_list' %}" class="back-link">Back to Product List</a> 
</body>

</html>